import Head from "next/head";
import Footer from "../src/components/Footer/Footer";
import Header from "../src/components/Header/Header";
import MainLayout from "../src/components/Layout/MainLayout";
import "../styles/globals.css";
import "../styles/general.sass";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Events Up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <Component {...pageProps} />
      </MainLayout>
    </>
  );
}
